id: P4017BDA1
initial_creation_type: input
source_metadata:
  Title: Advayasiddhiḥ
  Editor: Dr. Ram Prasad Mishra
  Publisher: Kant Publications
  Place of Publication: Delhi, India
  Year: '1995'
  Advayasiddhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:15:17.319977'
last_modified_at: '2022-03-08T16:15:17.319985'
